server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.25.10:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:${spring.application.name}.yaml
