server:
  port: 8200
spring:
  application:
    name: mq
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.25.10:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:${spring.application.name}.yaml
      - nacos:kafka.yaml
      - nacos:threadpool.yaml
